language: node_js
os: linux
dist: xenial
node_js:
  - "16"
jobs:
  include:
    - name: lint
      before_script:
        - npm install -g ajv-cli
      script: ajv validate -s schema.json -d data.json

